### ISSUE TITLE
Does it work.....plz tell

### ISSUE THREAD

**Issue by IshaanDixit07** [DmitrijVC/SomeShittyPythonScript#3]
pls tell if this works

**Comment by FssAy** [comment]
What do you mean if it works? It does generate random codes, checks them and redeem if valid. But chance of you getting one is around 0% + I didn't add any methods to bypass the rate limit, besides adding authorization with bot token. You could set a timeout at 1 second or smth, idk. Or add proxies, but that's slow.

**Comment by IshaanDixit07** [comment]
Ok fine

**Comment by IshaanDixit07** [comment]
@DmitrijVC this kind of thing should not exist cause 0% means a negative to me. Cause it takes time too!! Can you please try to make a discord code scraper which just gives you the code before the person can redeem it.(In simple words you just steal the code in mid-way. @DmitrijVC  plz reply

**Comment by IshaanDixit07** [comment]
@DmitrijVC  plz follow I would love to work with you when I grow up. I followed you!!

**Comment by FssAy** [comment]
> @DmitrijVC this kind of thing should not exist cause 0% means a negative to me. Cause it takes time too!! Can you please try to make a discord code scraper which just gives you the code before the person can redeem it.(In simple words you just steal the code in mid-way. @DmitrijVC plz reply

Please check out: https://github.com/lnxcz/nitro-generator/issues/8#issuecomment-764987352
I am a busy person, so if you need a Discord Sniper, use this one: https://github.com/Melonai/rust-nitro-sniper

**Comment by IshaanDixit07** [comment]
thanks for following
